//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  services: Services;
  servicesConnection: ServicesConnection;
  process: Process;
  processConnection: ProcessConnection;
  works: Works;
  worksConnection: WorksConnection;
  team: Team;
  teamConnection: TeamConnection;
  posts: Posts;
  postsConnection: PostsConnection;
  faq: Faq;
  faqConnection: FaqConnection;
  brands: Brands;
  brandsConnection: BrandsConnection;
  marquee: Marquee;
  marqueeConnection: MarqueeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryProcessArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProcessConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProcessFilter>;
};


export type QueryWorksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorksFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};


export type QueryBrandsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBrandsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BrandsFilter>;
};


export type QueryMarqueeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMarqueeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MarqueeFilter>;
};

export type DocumentFilter = {
  services?: InputMaybe<ServicesFilter>;
  process?: InputMaybe<ProcessFilter>;
  works?: InputMaybe<WorksFilter>;
  team?: InputMaybe<TeamFilter>;
  posts?: InputMaybe<PostsFilter>;
  faq?: InputMaybe<FaqFilter>;
  brands?: InputMaybe<BrandsFilter>;
  marquee?: InputMaybe<MarqueeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Services | Process | Works | Team | Posts | Faq | Brands | Marquee | Folder;

export type ServicesItems = {
  __typename?: 'ServicesItems';
  num?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  items?: Maybe<Array<Maybe<ServicesItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesItemsFilter = {
  num?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  items?: InputMaybe<ServicesItemsFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type ProcessItems = {
  __typename?: 'ProcessItems';
  num?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  deliverables?: Maybe<Scalars['String']['output']>;
};

export type Process = Node & Document & {
  __typename?: 'Process';
  items?: Maybe<Array<Maybe<ProcessItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProcessItemsFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  deliverables?: InputMaybe<StringFilter>;
};

export type ProcessFilter = {
  items?: InputMaybe<ProcessItemsFilter>;
};

export type ProcessConnectionEdges = {
  __typename?: 'ProcessConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Process>;
};

export type ProcessConnection = Connection & {
  __typename?: 'ProcessConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProcessConnectionEdges>>>;
};

export type WorksItemsBody = {
  __typename?: 'WorksItemsBody';
  h?: Maybe<Scalars['String']['output']>;
  p?: Maybe<Scalars['String']['output']>;
};

export type WorksItems = {
  __typename?: 'WorksItems';
  slug?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  client?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  team?: Maybe<Scalars['String']['output']>;
  gear?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Array<Maybe<WorksItemsBody>>>;
};

export type Works = Node & Document & {
  __typename?: 'Works';
  items?: Maybe<Array<Maybe<WorksItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WorksItemsBodyFilter = {
  h?: InputMaybe<StringFilter>;
  p?: InputMaybe<StringFilter>;
};

export type WorksItemsFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  client?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  team?: InputMaybe<StringFilter>;
  gear?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  body?: InputMaybe<WorksItemsBodyFilter>;
};

export type WorksFilter = {
  items?: InputMaybe<WorksItemsFilter>;
};

export type WorksConnectionEdges = {
  __typename?: 'WorksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Works>;
};

export type WorksConnection = Connection & {
  __typename?: 'WorksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorksConnectionEdges>>>;
};

export type TeamItems = {
  __typename?: 'TeamItems';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  short?: Maybe<Scalars['String']['output']>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  items?: Maybe<Array<Maybe<TeamItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamItemsFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  short?: InputMaybe<StringFilter>;
};

export type TeamFilter = {
  items?: InputMaybe<TeamItemsFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type PostsItemsBody = {
  __typename?: 'PostsItemsBody';
  h?: Maybe<Scalars['String']['output']>;
  p?: Maybe<Scalars['String']['output']>;
};

export type PostsItems = {
  __typename?: 'PostsItems';
  slug?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  read?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Array<Maybe<PostsItemsBody>>>;
};

export type Posts = Node & Document & {
  __typename?: 'Posts';
  items?: Maybe<Array<Maybe<PostsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PostsItemsBodyFilter = {
  h?: InputMaybe<StringFilter>;
  p?: InputMaybe<StringFilter>;
};

export type PostsItemsFilter = {
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  read?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  body?: InputMaybe<PostsItemsBodyFilter>;
};

export type PostsFilter = {
  items?: InputMaybe<PostsItemsFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type FaqItems = {
  __typename?: 'FaqItems';
  cat?: Maybe<Scalars['String']['output']>;
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  items?: Maybe<Array<Maybe<FaqItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqItemsFilter = {
  cat?: InputMaybe<StringFilter>;
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type FaqFilter = {
  items?: InputMaybe<FaqItemsFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Brands = Node & Document & {
  __typename?: 'Brands';
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BrandsFilter = {
  items?: InputMaybe<StringFilter>;
};

export type BrandsConnectionEdges = {
  __typename?: 'BrandsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Brands>;
};

export type BrandsConnection = Connection & {
  __typename?: 'BrandsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BrandsConnectionEdges>>>;
};

export type Marquee = Node & Document & {
  __typename?: 'Marquee';
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MarqueeFilter = {
  items?: InputMaybe<StringFilter>;
};

export type MarqueeConnectionEdges = {
  __typename?: 'MarqueeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Marquee>;
};

export type MarqueeConnection = Connection & {
  __typename?: 'MarqueeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MarqueeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateServices: Services;
  createServices: Services;
  updateProcess: Process;
  createProcess: Process;
  updateWorks: Works;
  createWorks: Works;
  updateTeam: Team;
  createTeam: Team;
  updatePosts: Posts;
  createPosts: Posts;
  updateFaq: Faq;
  createFaq: Faq;
  updateBrands: Brands;
  createBrands: Brands;
  updateMarquee: Marquee;
  createMarquee: Marquee;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateProcessArgs = {
  relativePath: Scalars['String']['input'];
  params: ProcessMutation;
};


export type MutationCreateProcessArgs = {
  relativePath: Scalars['String']['input'];
  params: ProcessMutation;
};


export type MutationUpdateWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: WorksMutation;
};


export type MutationCreateWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: WorksMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String']['input'];
  params: PostsMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationUpdateBrandsArgs = {
  relativePath: Scalars['String']['input'];
  params: BrandsMutation;
};


export type MutationCreateBrandsArgs = {
  relativePath: Scalars['String']['input'];
  params: BrandsMutation;
};


export type MutationUpdateMarqueeArgs = {
  relativePath: Scalars['String']['input'];
  params: MarqueeMutation;
};


export type MutationCreateMarqueeArgs = {
  relativePath: Scalars['String']['input'];
  params: MarqueeMutation;
};

export type DocumentUpdateMutation = {
  services?: InputMaybe<ServicesMutation>;
  process?: InputMaybe<ProcessMutation>;
  works?: InputMaybe<WorksMutation>;
  team?: InputMaybe<TeamMutation>;
  posts?: InputMaybe<PostsMutation>;
  faq?: InputMaybe<FaqMutation>;
  brands?: InputMaybe<BrandsMutation>;
  marquee?: InputMaybe<MarqueeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  services?: InputMaybe<ServicesMutation>;
  process?: InputMaybe<ProcessMutation>;
  works?: InputMaybe<WorksMutation>;
  team?: InputMaybe<TeamMutation>;
  posts?: InputMaybe<PostsMutation>;
  faq?: InputMaybe<FaqMutation>;
  brands?: InputMaybe<BrandsMutation>;
  marquee?: InputMaybe<MarqueeMutation>;
};

export type ServicesItemsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesMutation = {
  items?: InputMaybe<Array<InputMaybe<ServicesItemsMutation>>>;
};

export type ProcessItemsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  deliverables?: InputMaybe<Scalars['String']['input']>;
};

export type ProcessMutation = {
  items?: InputMaybe<Array<InputMaybe<ProcessItemsMutation>>>;
};

export type WorksItemsBodyMutation = {
  h?: InputMaybe<Scalars['String']['input']>;
  p?: InputMaybe<Scalars['String']['input']>;
};

export type WorksItemsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  client?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  team?: InputMaybe<Scalars['String']['input']>;
  gear?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Array<InputMaybe<WorksItemsBodyMutation>>>;
};

export type WorksMutation = {
  items?: InputMaybe<Array<InputMaybe<WorksItemsMutation>>>;
};

export type TeamItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  short?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  items?: InputMaybe<Array<InputMaybe<TeamItemsMutation>>>;
};

export type PostsItemsBodyMutation = {
  h?: InputMaybe<Scalars['String']['input']>;
  p?: InputMaybe<Scalars['String']['input']>;
};

export type PostsItemsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  read?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Array<InputMaybe<PostsItemsBodyMutation>>>;
};

export type PostsMutation = {
  items?: InputMaybe<Array<InputMaybe<PostsItemsMutation>>>;
};

export type FaqItemsMutation = {
  cat?: InputMaybe<Scalars['String']['input']>;
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  items?: InputMaybe<Array<InputMaybe<FaqItemsMutation>>>;
};

export type BrandsMutation = {
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type MarqueeMutation = {
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesPartsFragment = { __typename: 'Services', items?: Array<{ __typename: 'ServicesItems', num?: string | null, tag?: string | null, title?: string | null, desc?: string | null, items?: Array<string | null> | null } | null> | null };

export type ProcessPartsFragment = { __typename: 'Process', items?: Array<{ __typename: 'ProcessItems', num?: string | null, title?: string | null, desc?: string | null, deliverables?: string | null } | null> | null };

export type WorksPartsFragment = { __typename: 'Works', items?: Array<{ __typename: 'WorksItems', slug?: string | null, title?: string | null, client?: string | null, tag?: string | null, year?: string | null, category?: string | null, format?: string | null, team?: string | null, gear?: string | null, summary?: string | null, body?: Array<{ __typename: 'WorksItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', items?: Array<{ __typename: 'TeamItems', name?: string | null, role?: string | null, short?: string | null } | null> | null };

export type PostsPartsFragment = { __typename: 'Posts', items?: Array<{ __typename: 'PostsItems', slug?: string | null, date?: string | null, title?: string | null, excerpt?: string | null, read?: string | null, category?: string | null, body?: Array<{ __typename: 'PostsItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null };

export type FaqPartsFragment = { __typename: 'Faq', items?: Array<{ __typename: 'FaqItems', cat?: string | null, q?: string | null, a?: string | null } | null> | null };

export type BrandsPartsFragment = { __typename: 'Brands', items?: Array<string | null> | null };

export type MarqueePartsFragment = { __typename: 'Marquee', items?: Array<string | null> | null };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ServicesItems', num?: string | null, tag?: string | null, title?: string | null, desc?: string | null, items?: Array<string | null> | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ServicesItems', num?: string | null, tag?: string | null, title?: string | null, desc?: string | null, items?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type ProcessQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProcessQuery = { __typename?: 'Query', process: { __typename: 'Process', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProcessItems', num?: string | null, title?: string | null, desc?: string | null, deliverables?: string | null } | null> | null } };

export type ProcessConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProcessFilter>;
}>;


export type ProcessConnectionQuery = { __typename?: 'Query', processConnection: { __typename?: 'ProcessConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProcessConnectionEdges', cursor: string, node?: { __typename: 'Process', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'ProcessItems', num?: string | null, title?: string | null, desc?: string | null, deliverables?: string | null } | null> | null } | null } | null> | null } };

export type WorksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WorksQuery = { __typename?: 'Query', works: { __typename: 'Works', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'WorksItems', slug?: string | null, title?: string | null, client?: string | null, tag?: string | null, year?: string | null, category?: string | null, format?: string | null, team?: string | null, gear?: string | null, summary?: string | null, body?: Array<{ __typename: 'WorksItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null } };

export type WorksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorksFilter>;
}>;


export type WorksConnectionQuery = { __typename?: 'Query', worksConnection: { __typename?: 'WorksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WorksConnectionEdges', cursor: string, node?: { __typename: 'Works', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'WorksItems', slug?: string | null, title?: string | null, client?: string | null, tag?: string | null, year?: string | null, category?: string | null, format?: string | null, team?: string | null, gear?: string | null, summary?: string | null, body?: Array<{ __typename: 'WorksItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TeamItems', name?: string | null, role?: string | null, short?: string | null } | null> | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TeamItems', name?: string | null, role?: string | null, short?: string | null } | null> | null } | null } | null> | null } };

export type PostsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostsQuery = { __typename?: 'Query', posts: { __typename: 'Posts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PostsItems', slug?: string | null, date?: string | null, title?: string | null, excerpt?: string | null, read?: string | null, category?: string | null, body?: Array<{ __typename: 'PostsItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null } };

export type PostsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostsFilter>;
}>;


export type PostsConnectionQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostsConnectionEdges', cursor: string, node?: { __typename: 'Posts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'PostsItems', slug?: string | null, date?: string | null, title?: string | null, excerpt?: string | null, read?: string | null, category?: string | null, body?: Array<{ __typename: 'PostsItemsBody', h?: string | null, p?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqItems', cat?: string | null, q?: string | null, a?: string | null } | null> | null } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqItems', cat?: string | null, q?: string | null, a?: string | null } | null> | null } | null } | null> | null } };

export type BrandsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BrandsQuery = { __typename?: 'Query', brands: { __typename: 'Brands', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BrandsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BrandsFilter>;
}>;


export type BrandsConnectionQuery = { __typename?: 'Query', brandsConnection: { __typename?: 'BrandsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BrandsConnectionEdges', cursor: string, node?: { __typename: 'Brands', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MarqueeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MarqueeQuery = { __typename?: 'Query', marquee: { __typename: 'Marquee', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MarqueeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MarqueeFilter>;
}>;


export type MarqueeConnectionQuery = { __typename?: 'Query', marqueeConnection: { __typename?: 'MarqueeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MarqueeConnectionEdges', cursor: string, node?: { __typename: 'Marquee', id: string, items?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  items {
    __typename
    num
    tag
    title
    desc
    items
  }
}
    `;
export const ProcessPartsFragmentDoc = gql`
    fragment ProcessParts on Process {
  __typename
  items {
    __typename
    num
    title
    desc
    deliverables
  }
}
    `;
export const WorksPartsFragmentDoc = gql`
    fragment WorksParts on Works {
  __typename
  items {
    __typename
    slug
    title
    client
    tag
    year
    category
    format
    team
    gear
    summary
    body {
      __typename
      h
      p
    }
  }
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  items {
    __typename
    name
    role
    short
  }
}
    `;
export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  __typename
  items {
    __typename
    slug
    date
    title
    excerpt
    read
    category
    body {
      __typename
      h
      p
    }
  }
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  items {
    __typename
    cat
    q
    a
  }
}
    `;
export const BrandsPartsFragmentDoc = gql`
    fragment BrandsParts on Brands {
  __typename
  items
}
    `;
export const MarqueePartsFragmentDoc = gql`
    fragment MarqueeParts on Marquee {
  __typename
  items
}
    `;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ProcessDocument = gql`
    query process($relativePath: String!) {
  process(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProcessParts
  }
}
    ${ProcessPartsFragmentDoc}`;
export const ProcessConnectionDocument = gql`
    query processConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProcessFilter) {
  processConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProcessParts
      }
    }
  }
}
    ${ProcessPartsFragmentDoc}`;
export const WorksDocument = gql`
    query works($relativePath: String!) {
  works(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorksParts
  }
}
    ${WorksPartsFragmentDoc}`;
export const WorksConnectionDocument = gql`
    query worksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorksFilter) {
  worksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorksParts
      }
    }
  }
}
    ${WorksPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export const BrandsDocument = gql`
    query brands($relativePath: String!) {
  brands(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BrandsParts
  }
}
    ${BrandsPartsFragmentDoc}`;
export const BrandsConnectionDocument = gql`
    query brandsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BrandsFilter) {
  brandsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BrandsParts
      }
    }
  }
}
    ${BrandsPartsFragmentDoc}`;
export const MarqueeDocument = gql`
    query marquee($relativePath: String!) {
  marquee(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MarqueeParts
  }
}
    ${MarqueePartsFragmentDoc}`;
export const MarqueeConnectionDocument = gql`
    query marqueeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MarqueeFilter) {
  marqueeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MarqueeParts
      }
    }
  }
}
    ${MarqueePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    process(variables: ProcessQueryVariables, options?: C): Promise<{data: ProcessQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcessQueryVariables, query: string}> {
        return requester<{data: ProcessQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcessQueryVariables, query: string}, ProcessQueryVariables>(ProcessDocument, variables, options);
      },
    processConnection(variables?: ProcessConnectionQueryVariables, options?: C): Promise<{data: ProcessConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcessConnectionQueryVariables, query: string}> {
        return requester<{data: ProcessConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProcessConnectionQueryVariables, query: string}, ProcessConnectionQueryVariables>(ProcessConnectionDocument, variables, options);
      },
    works(variables: WorksQueryVariables, options?: C): Promise<{data: WorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksQueryVariables, query: string}> {
        return requester<{data: WorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksQueryVariables, query: string}, WorksQueryVariables>(WorksDocument, variables, options);
      },
    worksConnection(variables?: WorksConnectionQueryVariables, options?: C): Promise<{data: WorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksConnectionQueryVariables, query: string}> {
        return requester<{data: WorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksConnectionQueryVariables, query: string}, WorksConnectionQueryVariables>(WorksConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      },
    brands(variables: BrandsQueryVariables, options?: C): Promise<{data: BrandsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandsQueryVariables, query: string}> {
        return requester<{data: BrandsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandsQueryVariables, query: string}, BrandsQueryVariables>(BrandsDocument, variables, options);
      },
    brandsConnection(variables?: BrandsConnectionQueryVariables, options?: C): Promise<{data: BrandsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandsConnectionQueryVariables, query: string}> {
        return requester<{data: BrandsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BrandsConnectionQueryVariables, query: string}, BrandsConnectionQueryVariables>(BrandsConnectionDocument, variables, options);
      },
    marquee(variables: MarqueeQueryVariables, options?: C): Promise<{data: MarqueeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarqueeQueryVariables, query: string}> {
        return requester<{data: MarqueeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarqueeQueryVariables, query: string}, MarqueeQueryVariables>(MarqueeDocument, variables, options);
      },
    marqueeConnection(variables?: MarqueeConnectionQueryVariables, options?: C): Promise<{data: MarqueeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarqueeConnectionQueryVariables, query: string}> {
        return requester<{data: MarqueeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarqueeConnectionQueryVariables, query: string}, MarqueeConnectionQueryVariables>(MarqueeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  